2017-02-10 12:45:57.500 [error] <0.2094.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.2099.0> exit with reason normal in context child_terminated
2017-02-10 12:46:02.578 [error] <0.2179.0>@erlcass:session_create:346 session <0.2179.0> connection timeout
2017-02-10 12:46:02.579 [error] <0.2178.0>@erlcass_log:log_message:36 <<"Unable to establish a control connection to host 10.224.45.95 because of the following error: Connection timeout">> on <<"virtual void cass::ControlConnection::on_close(cass::Connection*)">> at file src/control_connection.cpp line 263
2017-02-10 12:46:02.579 [error] <0.2179.0> CRASH REPORT Process erlcass with 0 neighbours exited with reason: bad return value: {stop,{error,connect_session_timeout},shutdown,{state,undefined}} in gen_server:init_it/6 line 356
2017-02-10 12:46:02.579 [error] <0.2177.0> Supervisor erlcass_sup had child erlcass started with erlcass:start_link() at undefined exit with reason bad return value: {stop,{error,connect_session_timeout},shutdown,{state,undefined}} in context start_error
2017-02-10 12:46:02.579 [error] <0.2174.0> CRASH REPORT Process <0.2174.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,erlcass,{bad_return_value,{stop,{error,connect_session_timeout},shutdown,{state,undefined}}}}},{erlcass_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-02-10 12:46:32.017 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
